# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'prepesquisa.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_pesquisa(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("font: 14pt \"Constantia\";")
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 641, 31))
        self.frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(0, 181, 198, 255), stop:1 rgba(255, 255, 255, 224));")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 450, 641, 31))
        self.frame_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(108, 168, 218, 255));")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(460, 40, 171, 161))
        self.frame_3.setToolTipDuration(1)
        self.frame_3.setStyleSheet("border-image: url(logo-_simbolo-removebg-preview.png);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.botaosair = QtWidgets.QPushButton(self.centralwidget)
        self.botaosair.setGeometry(QtCore.QRect(10, 400, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.botaosair.setFont(font)
        self.botaosair.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botaosair.setStyleSheet("QPushButton{\n"
"background-color: rgb(72, 187, 198);\n"
"border-radius: 5px;    \n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(72, 187, 198);\n"
"border-radius: 5px;    \n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(255 , 255, 255);\n"
"border-radius: 5px;    \n"
"}\n"
"")
        self.botaosair.setObjectName("botaosair")
        self.botaovoltar = QtWidgets.QPushButton(self.centralwidget)
        self.botaovoltar.setGeometry(QtCore.QRect(500, 400, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.botaovoltar.setFont(font)
        self.botaovoltar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botaovoltar.setStyleSheet("QPushButton{\n"
"background-color: rgb(72, 187, 198);\n"
"border-radius: 5px;    \n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(72, 187, 198);\n"
"border-radius: 5px;    \n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(255 , 255, 255);\n"
"border-radius: 5px;    \n"
"}\n"
"")
        self.botaovoltar.setObjectName("botaovoltar")
        self.label_principal = QtWidgets.QLabel(self.centralwidget)
        self.label_principal.setGeometry(QtCore.QRect(215, 80, 251, 50))
        self.label_principal.setStyleSheet("\n"
"color: rgb(108, 168, 218);")
        self.label_principal.setObjectName("label_principal")
        self.comboregio = QtWidgets.QComboBox(self.centralwidget)
        self.comboregio.setEnabled(True)
        self.comboregio.setGeometry(QtCore.QRect(350, 160, 111, 31))
        self.comboregio.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboregio.setStyleSheet("\n"
"font: 12pt \"Constantia\";")
        self.comboregio.setObjectName("comboregio")
        self.comboregio.addItem("")
        self.comboregio.addItem("")
        self.comboregio.addItem("")
        self.comboregio.addItem("")
        self.comboregio.addItem("")
        self.comboregio.addItem("")
        self.label_regiao = QtWidgets.QLabel(self.centralwidget)
        self.label_regiao.setGeometry(QtCore.QRect(170, 160, 171, 31))
        self.label_regiao.setObjectName("label_regiao")
        self.label_tempo = QtWidgets.QLabel(self.centralwidget)
        self.label_tempo.setGeometry(QtCore.QRect(170, 200, 181, 31))
        self.label_tempo.setObjectName("label_tempo")
        self.combotempo = QtWidgets.QComboBox(self.centralwidget)
        self.combotempo.setGeometry(QtCore.QRect(350, 200, 111, 31))
        self.combotempo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.combotempo.setStyleSheet("\n"
"font: 12pt \"Constantia\";")
        self.combotempo.setObjectName("combotempo")
        self.combotempo.addItem("")
        self.combotempo.addItem("")
        self.combotempo.addItem("")
        self.combotempo.addItem("")
        self.combotempo.addItem("")
        self.combotempo.addItem("")
        self.combotempo.addItem("")
        self.combotempo.addItem("")
        self.botaopesquisa = QtWidgets.QPushButton(self.centralwidget)
        self.botaopesquisa.setGeometry(QtCore.QRect(240, 300, 171, 41))
        self.botaopesquisa.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botaopesquisa.setStyleSheet("QPushButton{\n"
"background-color: rgb(72, 187, 198);\n"
"border-radius: 5px;    \n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(72, 187, 198);\n"
"border-radius: 5px;    \n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(255 , 255, 255);\n"
"border-radius: 5px;    \n"
"}\n"
"")
        self.botaopesquisa.setObjectName("botaopesquisa")
        self.label_sexo = QtWidgets.QLabel(self.centralwidget)
        self.label_sexo.setGeometry(QtCore.QRect(190, 240, 111, 21))
        self.label_sexo.setObjectName("label_sexo")
        self.combosexo = QtWidgets.QComboBox(self.centralwidget)
        self.combosexo.setGeometry(QtCore.QRect(350, 240, 111, 31))
        self.combosexo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.combosexo.setStyleSheet("\n"
"font: 12pt \"Constantia\";")
        self.combosexo.setObjectName("combosexo")
        self.combosexo.addItem("")
        self.combosexo.addItem("")
        self.combosexo.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.botaosair.setText(_translate("MainWindow", "SAIR"))
        self.botaovoltar.setText(_translate("MainWindow", "VOLTAR"))
        self.label_principal.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">Pesquisa de Sintomas!</span></p></body></html>"))
        self.comboregio.setItemText(0, _translate("MainWindow", "Nordeste"))
        self.comboregio.setItemText(1, _translate("MainWindow", "Nenhum"))
        self.comboregio.setItemText(2, _translate("MainWindow", "Sudeste"))
        self.comboregio.setItemText(3, _translate("MainWindow", "Sul"))
        self.comboregio.setItemText(4, _translate("MainWindow", "Centro-Oeste"))
        self.comboregio.setItemText(5, _translate("MainWindow", "Norte"))
        self.label_regiao.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Selecione sua região:</span></p></body></html>"))
        self.label_tempo.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Tempo dos sintomas:</span></p></body></html>"))
        self.combotempo.setItemText(0, _translate("MainWindow", "1-4 Dias"))
        self.combotempo.setItemText(1, _translate("MainWindow", "Não sei dizer"))
        self.combotempo.setItemText(2, _translate("MainWindow", "5-6 Dias"))
        self.combotempo.setItemText(3, _translate("MainWindow", "1 Semana"))
        self.combotempo.setItemText(4, _translate("MainWindow", "2 Semanas"))
        self.combotempo.setItemText(5, _translate("MainWindow", "Mais de 2 semanas "))
        self.combotempo.setItemText(6, _translate("MainWindow", "Mais de 1 mês"))
        self.combotempo.setItemText(7, _translate("MainWindow", "Mais de 1 ano"))
        self.botaopesquisa.setText(_translate("MainWindow", "Pesquisa Guiada!"))
        self.label_sexo.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Sexo biologico:</span></p></body></html>"))
        self.combosexo.setItemText(0, _translate("MainWindow", "Masculino"))
        self.combosexo.setItemText(1, _translate("MainWindow", "Feminino"))
        self.combosexo.setItemText(2, _translate("MainWindow", "Prefiro-não-dizer"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Tela_pesquisa()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
