# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu1.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_Menu(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        MainWindow.setStyleSheet("background-color: rgb(139, 164, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 14pt \"Constantia\";")
        self.centralwidget.setObjectName("centralwidget")
        self.labelmenu = QtWidgets.QLabel(self.centralwidget)
        self.labelmenu.setGeometry(QtCore.QRect(210, 90, 251, 50))
        self.labelmenu.setStyleSheet("\n"
"color: rgb(108, 168, 218);")
        self.labelmenu.setObjectName("labelmenu")
        self.botaovoltar = QtWidgets.QPushButton(self.centralwidget)
        self.botaovoltar.setGeometry(QtCore.QRect(10, 400, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.botaovoltar.setFont(font)
        self.botaovoltar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botaovoltar.setStyleSheet("QPushButton{\n"
"background-color: rgb(72, 187, 198);\n"
"border-radius: 5px;    \n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(72, 187, 198);\n"
"border-radius: 5px;    \n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(255 , 255, 255);\n"
"border-radius: 5px;    \n"
"}\n"
"")
        self.botaovoltar.setObjectName("botaovoltar")
        self.botaosair = QtWidgets.QPushButton(self.centralwidget)
        self.botaosair.setGeometry(QtCore.QRect(500, 400, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.botaosair.setFont(font)
        self.botaosair.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botaosair.setStyleSheet("QPushButton{\n"
"background-color: rgb(72, 187, 198);\n"
"border-radius: 5px;    \n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(72, 187, 198);\n"
"border-radius: 5px;    \n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(255 , 255, 255);\n"
"border-radius: 5px;    \n"
"}\n"
"")
        self.botaosair.setObjectName("botaosair")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 641, 31))
        self.frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(0, 181, 198, 255), stop:1 rgba(255, 255, 255, 224));")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 450, 641, 31))
        self.frame_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(108, 168, 218, 255));")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.botaoconsulta = QtWidgets.QPushButton(self.centralwidget)
        self.botaoconsulta.setGeometry(QtCore.QRect(250, 160, 171, 31))
        self.botaoconsulta.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botaoconsulta.setStyleSheet("QPushButton{\n"
"background-color: rgb(72, 187, 198);\n"
"border-radius: 5px;    \n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(72, 187, 198);\n"
"border-radius: 5px;    \n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(255 , 255, 255);\n"
"border-radius: 5px;    \n"
"}\n"
"")
        self.botaoconsulta.setObjectName("botaoconsulta")
        self.botaovacina = QtWidgets.QPushButton(self.centralwidget)
        self.botaovacina.setGeometry(QtCore.QRect(250, 210, 171, 31))
        self.botaovacina.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botaovacina.setStyleSheet("QPushButton{\n"
"background-color: rgb(72, 187, 198);\n"
"border-radius: 5px;    \n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(72, 187, 198);\n"
"border-radius: 5px;    \n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(255 , 255, 255);\n"
"border-radius: 5px;    \n"
"}\n"
"")
        self.botaovacina.setObjectName("botaovacina")
        self.botaonos = QtWidgets.QPushButton(self.centralwidget)
        self.botaonos.setGeometry(QtCore.QRect(250, 260, 171, 31))
        self.botaonos.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botaonos.setStyleSheet("QPushButton{\n"
"background-color: rgb(72, 187, 198);\n"
"border-radius: 5px;    \n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(72, 187, 198);\n"
"border-radius: 5px;    \n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(255 , 255, 255);\n"
"border-radius: 5px;    \n"
"}\n"
"")
        self.botaonos.setObjectName("botaonos")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(460, 40, 171, 161))
        self.frame_3.setStyleSheet("image: url(:/simbolo/logo-_simbolo-removebg-preview.png);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelmenu.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">Menu do Sistema</span></p></body></html>"))
        self.botaovoltar.setText(_translate("MainWindow", "VOLTAR"))
        self.botaosair.setText(_translate("MainWindow", "SAIR"))
        self.botaoconsulta.setText(_translate("MainWindow", "Sua consulta!"))
        self.botaovacina.setText(_translate("MainWindow", "Vacina!"))
        self.botaonos.setText(_translate("MainWindow", "Sobre Nós!"))
#import simbolo_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Tela_Menu()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
