# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Suporte.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_suporte(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 641, 31))
        self.frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(0, 181, 198, 255), stop:1 rgba(255, 255, 255, 224));")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(0, 450, 641, 31))
        self.frame_4.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(108, 168, 218, 255));")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_principal = QtWidgets.QLabel(self.centralwidget)
        self.label_principal.setGeometry(QtCore.QRect(260, 70, 151, 71))
        self.label_principal.setStyleSheet("font: 22pt \"Constantia\";\n"
"color: rgb(108, 168, 218);")
        self.label_principal.setObjectName("label_principal")
        self.privacidade = QtWidgets.QTextBrowser(self.centralwidget)
        self.privacidade.setGeometry(QtCore.QRect(30, 150, 331, 192))
        self.privacidade.setObjectName("privacidade")
        self.botaosair = QtWidgets.QPushButton(self.centralwidget)
        self.botaosair.setGeometry(QtCore.QRect(10, 400, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.botaosair.setFont(font)
        self.botaosair.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botaosair.setStyleSheet("QPushButton{\n"
"background-color: rgb(72, 187, 198);\n"
"border-radius: 5px;    \n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(72, 187, 198);\n"
"border-radius: 5px;    \n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(255 , 255, 255);\n"
"border-radius: 5px;    \n"
"}\n"
"")
        self.botaosair.setObjectName("botaosair")
        self.botaovoltar = QtWidgets.QPushButton(self.centralwidget)
        self.botaovoltar.setGeometry(QtCore.QRect(500, 400, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.botaovoltar.setFont(font)
        self.botaovoltar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botaovoltar.setStyleSheet("QPushButton{\n"
"background-color: rgb(72, 187, 198);\n"
"border-radius: 5px;    \n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(72, 187, 198);\n"
"border-radius: 5px;    \n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(255 , 255, 255);\n"
"border-radius: 5px;    \n"
"}\n"
"")
        self.botaovoltar.setObjectName("botaovoltar")
        self.label_contato = QtWidgets.QLabel(self.centralwidget)
        self.label_contato.setGeometry(QtCore.QRect(460, 140, 111, 31))
        self.label_contato.setStyleSheet("font: 16pt \"Constantia\";\n"
"\n"
"color: rgb(108, 168, 218);")
        self.label_contato.setObjectName("label_contato")
        self.label_insta_logo = QtWidgets.QLabel(self.centralwidget)
        self.label_insta_logo.setGeometry(QtCore.QRect(400, 190, 41, 41))
        self.label_insta_logo.setText("")
        self.label_insta_logo.setPixmap(QtGui.QPixmap("../../../../../../luiz/Design/conteudo/insta.png"))
        self.label_insta_logo.setScaledContents(True)
        self.label_insta_logo.setObjectName("label_insta_logo")
        self.label_telefone = QtWidgets.QLabel(self.centralwidget)
        self.label_telefone.setGeometry(QtCore.QRect(400, 250, 41, 41))
        self.label_telefone.setText("")
        self.label_telefone.setPixmap(QtGui.QPixmap("../../../../../../luiz/Design/conteudo/telefone fixo.png"))
        self.label_telefone.setScaledContents(True)
        self.label_telefone.setObjectName("label_telefone")
        self.label_insta = QtWidgets.QLabel(self.centralwidget)
        self.label_insta.setGeometry(QtCore.QRect(460, 190, 121, 31))
        self.label_insta.setObjectName("label_insta")
        self.label_numero = QtWidgets.QLabel(self.centralwidget)
        self.label_numero.setGeometry(QtCore.QRect(470, 250, 101, 41))
        self.label_numero.setObjectName("label_numero")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_principal.setText(_translate("MainWindow", "Suporte!"))
        self.privacidade.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">Política de Privacidade do Suporte</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">A sua privacidade é de extrema importância para nós. Esta política de privacidade explica como as informações pessoais que você fornece ao nosso serviço de suporte serão usadas, armazenadas e protegidas. Solicitamos que você leia atentamente esta política para entender como cuidamos dos seus dados.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">Coleta de Informações</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Quando você entra em contato com nosso serviço de suporte, podemos coletar informações pessoais, como seu nome, endereço de e-mail e número de telefone, para ajudar a identificá-lo e fornecer assistência adequada. Podemos também coletar informações técnicas relacionadas ao seu dispositivo ou sistema, como endereço IP e informações do navegador, para diagnosticar e resolver problemas técnicos.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">Uso das Informações</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">As informações pessoais que coletamos são utilizadas exclusivamente para fins de suporte e assistência ao cliente. Isso inclui o fornecimento de soluções para problemas relatados, respostas a consultas, informações sobre produtos ou serviços, e a melhoria contínua de nossos serviços.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">Armazenamento de Dados</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">As informações coletadas são armazenadas com a máxima segurança e confidencialidade. Empregamos medidas de segurança técnicas e organizacionais para proteger seus dados contra acesso não autorizado, uso indevido ou divulgação.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">Compartilhamento de Informações</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Não compartilhamos suas informações pessoais com terceiros, a menos que seja necessário para fornecer suporte efetivo ou cumprir com obrigações legais.</span></p></body></html>"))
        self.botaosair.setText(_translate("MainWindow", "SAIR"))
        self.botaovoltar.setText(_translate("MainWindow", "VOLTAR"))
        self.label_contato.setText(_translate("MainWindow", "Contato:"))
        self.label_insta.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">@suasaude</span></p></body></html>"))
        self.label_numero.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">4002-8922</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Tela_suporte()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
